name: Python Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # This will use /home/robertoteigeiro/Documents/pytest/requirements.txt
      - name: Ejecutar pruebas con pytest
        run: cd test-suma && pytest # Changed to run pytest within the test-suma directory
